term = require("term")
term.clear()
--term.cursor.save()
--term.cursor.restore()
term.cursor.jump(1,1)
io.stdout\write(term.colors.red .. "Starting..." .. term.colors.reset)
--term.cursor.restore()
term.cursor.jump(1,3)
--term.cursor.goup(1)
term.cleareol()
--term.cursor.goleft(3)
io.stdout\write(term.colors.blue .. "Ready" .. term.colors.reset)
print("")
